import type { Job, Company } from "./types"

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "TechCorp",
    location: "San Francisco, CA (Remote)",
    type: "Full-time",
    salary: "120K - 150K",
    description:
      "We're looking for a Senior Frontend Developer to join our team. You'll be responsible for building user interfaces for our web applications using React, Next.js, and TypeScript.",
    requirements: [
      "5+ years of experience with React",
      "Experience with Next.js and TypeScript",
      "Strong understanding of web performance optimization",
      "Experience with state management libraries like Redux or Zustand",
      "Experience with CSS-in-JS libraries like styled-components or emotion",
    ],
    responsibilities: [
      "Build and maintain user interfaces for our web applications",
      "Collaborate with designers and backend developers",
      "Write clean, maintainable, and testable code",
      "Participate in code reviews and provide feedback",
      "Mentor junior developers",
    ],
    postedAt: "2 days ago",
    tags: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    featured: true,
    companyDescription: "TechCorp is a leading technology company that builds innovative products for the web.",
    companyWebsite: "https://techcorp.com",
    applicationUrl: "https://techcorp.com/careers/senior-frontend-developer",
    applicationEmail: "careers@techcorp.com",
  },
  {
    id: "2",
    title: "Backend Developer",
    company: "DataSystems",
    location: "New York, NY",
    type: "Full-time",
    salary: "110K - 140K",
    description:
      "We're looking for a Backend Developer to join our team. You'll be responsible for building and maintaining our APIs and services using Node.js and Express.",
    requirements: [
      "3+ years of experience with Node.js",
      "Experience with Express or similar frameworks",
      "Strong understanding of RESTful APIs",
      "Experience with databases like MongoDB or PostgreSQL",
      "Knowledge of authentication and authorization",
    ],
    responsibilities: [
      "Build and maintain APIs and services",
      "Design and implement database schemas",
      "Write clean, maintainable, and testable code",
      "Participate in code reviews and provide feedback",
      "Collaborate with frontend developers",
    ],
    postedAt: "1 week ago",
    tags: ["Node.js", "Express", "MongoDB", "REST API"],
    featured: false,
    companyDescription: "DataSystems is a data-driven company that builds scalable solutions for businesses.",
    companyWebsite: "https://datasystems.com",
    applicationUrl: "https://datasystems.com/careers/backend-developer",
    applicationEmail: "careers@datasystems.com",
  },
  {
    id: "3",
    title: "Full Stack Developer",
    company: "WebSolutions",
    location: "Remote",
    type: "Full-time",
    salary: "100K - 130K",
    description:
      "We're looking for a Full Stack Developer to join our team. You'll be responsible for building and maintaining our web applications using React, Node.js, and MongoDB.",
    requirements: [
      "3+ years of experience with React",
      "3+ years of experience with Node.js",
      "Experience with MongoDB or similar NoSQL databases",
      "Strong understanding of RESTful APIs",
      "Experience with state management libraries like Redux or Zustand",
    ],
    responsibilities: [
      "Build and maintain web applications",
      "Design and implement database schemas",
      "Write clean, maintainable, and testable code",
      "Participate in code reviews and provide feedback",
      "Collaborate with designers and product managers",
    ],
    postedAt: "3 days ago",
    tags: ["React", "Node.js", "MongoDB", "Full Stack"],
    featured: true,
    companyDescription: "WebSolutions is a web development agency that builds custom solutions for businesses.",
    companyWebsite: "https://websolutions.com",
    applicationUrl: "https://websolutions.com/careers/full-stack-developer",
    applicationEmail: "careers@websolutions.com",
  },
  {
    id: "4",
    title: "UI/UX Designer",
    company: "DesignStudio",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "90K - 120K",
    description:
      "We're looking for a UI/UX Designer to join our team. You'll be responsible for designing user interfaces for our web and mobile applications.",
    requirements: [
      "3+ years of experience in UI/UX design",
      "Experience with design tools like Figma or Sketch",
      "Strong understanding of user-centered design principles",
      "Experience with design systems",
      "Knowledge of HTML, CSS, and JavaScript",
    ],
    responsibilities: [
      "Design user interfaces for web and mobile applications",
      "Create wireframes, prototypes, and high-fidelity designs",
      "Collaborate with developers to implement designs",
      "Conduct user research and usability testing",
      "Maintain and evolve our design system",
    ],
    postedAt: "5 days ago",
    tags: ["UI/UX", "Figma", "Design Systems", "User Research"],
    featured: false,
    companyDescription: "DesignStudio is a design agency that creates beautiful and functional user interfaces.",
    companyWebsite: "https://designstudio.com",
    applicationUrl: "https://designstudio.com/careers/ui-ux-designer",
    applicationEmail: "careers@designstudio.com",
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CloudTech",
    location: "Seattle, WA (Hybrid)",
    type: "Full-time",
    salary: "130K - 160K",
    description:
      "We're looking for a DevOps Engineer to join our team. You'll be responsible for building and maintaining our infrastructure and CI/CD pipelines.",
    requirements: [
      "3+ years of experience in DevOps",
      "Experience with cloud platforms like AWS, Azure, or GCP",
      "Experience with containerization technologies like Docker and Kubernetes",
      "Experience with CI/CD tools like Jenkins, GitHub Actions, or CircleCI",
      "Knowledge of infrastructure as code tools like Terraform or CloudFormation",
    ],
    responsibilities: [
      "Build and maintain our infrastructure",
      "Set up and maintain CI/CD pipelines",
      "Monitor and optimize system performance",
      "Implement security best practices",
      "Collaborate with developers to deploy applications",
    ],
    postedAt: "1 week ago",
    tags: ["DevOps", "AWS", "Docker", "Kubernetes", "CI/CD"],
    featured: false,
    companyDescription: "CloudTech is a cloud infrastructure company that helps businesses scale their applications.",
    companyWebsite: "https://cloudtech.com",
    applicationUrl: "https://cloudtech.com/careers/devops-engineer",
    applicationEmail: "careers@cloudtech.com",
  },
  {
    id: "6",
    title: "Product Manager",
    company: "ProductLabs",
    location: "Boston, MA",
    type: "Full-time",
    salary: "120K - 150K",
    description:
      "We're looking for a Product Manager to join our team. You'll be responsible for defining and executing the product strategy for our web applications.",
    requirements: [
      "3+ years of experience in product management",
      "Experience with agile methodologies",
      "Strong understanding of user-centered design principles",
      "Experience with product analytics tools",
      "Excellent communication and leadership skills",
    ],
    responsibilities: [
      "Define and execute the product strategy",
      "Gather and prioritize product requirements",
      "Work with designers and developers to build products",
      "Analyze product metrics and make data-driven decisions",
      "Communicate product updates to stakeholders",
    ],
    postedAt: "2 weeks ago",
    tags: ["Product Management", "Agile", "User Research", "Analytics"],
    featured: false,
    companyDescription: "ProductLabs is a product development company that builds innovative solutions for businesses.",
    companyWebsite: "https://productlabs.com",
    applicationUrl: "https://productlabs.com/careers/product-manager",
    applicationEmail: "careers@productlabs.com",
  },
  {
    id: "7",
    title: "Data Scientist",
    company: "DataInsights",
    location: "Remote",
    type: "Full-time",
    salary: "110K - 140K",
    description:
      "We're looking for a Data Scientist to join our team. You'll be responsible for analyzing data and building machine learning models to solve business problems.",
    requirements: [
      "3+ years of experience in data science",
      "Experience with Python and data science libraries like pandas, NumPy, and scikit-learn",
      "Strong understanding of machine learning algorithms",
      "Experience with data visualization tools",
      "Knowledge of SQL and databases",
    ],
    responsibilities: [
      "Analyze data and identify patterns",
      "Build and deploy machine learning models",
      "Create data visualizations and reports",
      "Collaborate with product managers and engineers",
      "Present findings to stakeholders",
    ],
    postedAt: "3 days ago",
    tags: ["Data Science", "Python", "Machine Learning", "SQL"],
    featured: false,
    companyDescription: "DataInsights is a data analytics company that helps businesses make data-driven decisions.",
    companyWebsite: "https://datainsights.com",
    applicationUrl: "https://datainsights.com/careers/data-scientist",
    applicationEmail: "careers@datainsights.com",
  },
  {
    id: "8",
    title: "Mobile Developer",
    company: "AppWorks",
    location: "Austin, TX",
    type: "Full-time",
    salary: "100K - 130K",
    description:
      "We're looking for a Mobile Developer to join our team. You'll be responsible for building and maintaining our mobile applications using React Native.",
    requirements: [
      "3+ years of experience in mobile development",
      "Experience with React Native",
      "Experience with state management libraries like Redux or MobX",
      "Strong understanding of mobile UI/UX principles",
      "Knowledge of native mobile development is a plus",
    ],
    responsibilities: [
      "Build and maintain mobile applications",
      "Write clean, maintainable, and testable code",
      "Collaborate with designers and backend developers",
      "Participate in code reviews and provide feedback",
      "Optimize applications for performance",
    ],
    postedAt: "1 week ago",
    tags: ["React Native", "Mobile", "JavaScript", "Redux"],
    featured: false,
    companyDescription: "AppWorks is a mobile app development company that builds innovative solutions for businesses.",
    companyWebsite: "https://appworks.com",
    applicationUrl: "https://appworks.com/careers/mobile-developer",
    applicationEmail: "careers@appworks.com",
  },
]

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp",
    description: "TechCorp is a leading technology company that builds innovative products for the web.",
    website: "https://techcorp.com",
    location: "San Francisco, CA",
    industry: "Technology",
    size: "501-1000 employees",
    founded: "2010",
    jobs: mockJobs.filter((job) => job.company === "TechCorp"),
  },
  {
    id: "2",
    name: "DataSystems",
    description: "DataSystems is a data-driven company that builds scalable solutions for businesses.",
    website: "https://datasystems.com",
    location: "New York, NY",
    industry: "Technology",
    size: "201-500 employees",
    founded: "2012",
    jobs: mockJobs.filter((job) => job.company === "DataSystems"),
  },
  {
    id: "3",
    name: "WebSolutions",
    description: "WebSolutions is a web development agency that builds custom solutions for businesses.",
    website: "https://websolutions.com",
    location: "Remote",
    industry: "Web Development",
    size: "51-200 employees",
    founded: "2015",
    jobs: mockJobs.filter((job) => job.company === "WebSolutions"),
  },
  {
    id: "4",
    name: "DesignStudio",
    description: "DesignStudio is a design agency that creates beautiful and functional user interfaces.",
    website: "https://designstudio.com",
    location: "Los Angeles, CA",
    industry: "Design",
    size: "11-50 employees",
    founded: "2018",
    jobs: mockJobs.filter((job) => job.company === "DesignStudio"),
  },
]

